name       : rssguard
version    : 4.5.0
release    : 1
source     :
    - https://github.com/martinrotter/rssguard/archive/refs/tags/4.5.0.tar.gz : 0a5bf5858577cfc741164f072e4f06125ece83db505af77eb05ed9faa81ac7f2
license    : GPL-3.0-or-later
homepage   : https://github.com/martinrotter/rssguard
component  : network.news
summary    : Simple (yet powerful) Qt feed reader
description: |
    Simple (yet powerful) Qt feed reader
builddeps  :
    - pkgconfig(Qt5Multimedia)
    - pkgconfig(Qt5Qml)
    - pkgconfig(Qt5WebEngineWidgets)
    - pkgconfig(dbus-1)
    - pkgconfig(sqlite3)
    - qt5-tools-devel # linguist
setup      : |
    %cmake_ninja -DBUILD_WITH_QT6=OFF \
                 -DNO_UPDATE_CHECK=ON \
                 -DREVISION_FROM_GIT=OFF \
                 -DUSE_SYSTEM_SQLITE=ON \
                 -DUSE_WEBENGINE=ON
build      : |
    %ninja_build
install    : |
    %ninja_install
patterns   :
    - /usr/lib64/librssguard.so
